# Generated by Django 2.1.3 on 2018-11-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
