# Generated by Django 2.0.7 on 2018-08-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180803_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
