# Generated by Django 2.1.1 on 2018-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='id',
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='post_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
