# Generated by Django 2.1.3 on 2018-11-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181108_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
